"""base builder

Revision ID: 0001
Revises:
Create Date: 2026-10-01 18:55:34.089913

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "0001"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


# Immutability rules from HLD §0: handles never change, versions never change after insert,
# and a mapping's agent must be the agent of its version. One statement per entry (asyncpg).
TRIGGERS = [
    """
    CREATE FUNCTION agents_handle_immutable() RETURNS trigger AS $$
    BEGIN
      IF NEW.handle <> OLD.handle THEN
        RAISE EXCEPTION 'agents.handle is immutable' USING ERRCODE = 'check_violation';
      END IF;
      RETURN NEW;
    END $$ LANGUAGE plpgsql
    """,
    """
    CREATE TRIGGER agents_handle_immutable BEFORE UPDATE ON agents
      FOR EACH ROW EXECUTE FUNCTION agents_handle_immutable()
    """,
    """
    CREATE FUNCTION agent_prompts_immutable() RETURNS trigger AS $$
    BEGIN
      IF NEW.config IS DISTINCT FROM OLD.config OR NEW.config_hash <> OLD.config_hash
         OR NEW.version <> OLD.version OR NEW.agent_id <> OLD.agent_id THEN
        RAISE EXCEPTION 'agent_prompts versions are immutable' USING ERRCODE = 'check_violation';
      END IF;
      RETURN NEW;
    END $$ LANGUAGE plpgsql
    """,
    """
    CREATE TRIGGER agent_prompts_immutable BEFORE UPDATE ON agent_prompts
      FOR EACH ROW EXECUTE FUNCTION agent_prompts_immutable()
    """,
    """
    CREATE FUNCTION compiled_agent_firm_mappings_agent_matches_version() RETURNS trigger AS $$
    BEGIN
      IF NOT EXISTS (
        SELECT 1 FROM agent_prompts p WHERE p.id = NEW.agent_prompt_id AND p.agent_id = NEW.agent_id
      ) THEN
        RAISE EXCEPTION 'mapping agent_id must match its version' USING ERRCODE = 'check_violation';
      END IF;
      RETURN NEW;
    END $$ LANGUAGE plpgsql
    """,
    """
    CREATE TRIGGER compiled_agent_firm_mappings_agent_matches_version
      BEFORE INSERT OR UPDATE ON compiled_agent_firm_mappings
      FOR EACH ROW EXECUTE FUNCTION compiled_agent_firm_mappings_agent_matches_version()
    """,
]
DROP_TRIGGERS = [
    "DROP TRIGGER IF EXISTS compiled_agent_firm_mappings_agent_matches_version"
    " ON compiled_agent_firm_mappings",
    "DROP FUNCTION IF EXISTS compiled_agent_firm_mappings_agent_matches_version()",
    "DROP TRIGGER IF EXISTS agent_prompts_immutable ON agent_prompts",
    "DROP FUNCTION IF EXISTS agent_prompts_immutable()",
    "DROP TRIGGER IF EXISTS agents_handle_immutable ON agents",
    "DROP FUNCTION IF EXISTS agents_handle_immutable()",
]
# Trigram search over name and description (not expressible in the ORM; env.py ignores it).
SEARCH_INDEX = (
    "CREATE INDEX agents_search_trgm_idx ON agents"
    " USING gin ((name || ' ' || description) gin_trgm_ops)"
)


def upgrade() -> None:
    """Upgrade schema."""
    op.execute("CREATE EXTENSION IF NOT EXISTS pgcrypto")  # gen_random_uuid()
    op.execute("CREATE EXTENSION IF NOT EXISTS pg_trgm")
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "agents",
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("handle", sa.Text(), nullable=False),
        sa.Column("name", sa.Text(), nullable=False),
        sa.Column("description", sa.Text(), server_default="", nullable=False),
        sa.Column("use_cases", postgresql.ARRAY(sa.Text()), server_default="{}", nullable=False),
        sa.Column("is_template", sa.Boolean(), server_default="false", nullable=False),
        sa.Column("source_agent_id", sa.UUID(), nullable=True),
        sa.Column("is_callable", sa.Boolean(), server_default="true", nullable=False),
        sa.Column("auto_delegate", sa.Boolean(), server_default="false", nullable=False),
        sa.Column("version_policy", sa.Text(), server_default="pin", nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.CheckConstraint(
            "handle ~ '^[a-z][a-z0-9_-]{2,31}$'", name=op.f("agents_handle_format_check")
        ),
        sa.CheckConstraint(
            "version_policy IN ('pin','follow_active_at_cycle')",
            name=op.f("agents_version_policy_check"),
        ),
        sa.CheckConstraint("cardinality(use_cases) <= 20", name=op.f("agents_use_cases_max_check")),
        sa.ForeignKeyConstraint(
            ["source_agent_id"], ["agents.id"], name=op.f("agents_source_agent_id_fkey")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("agents_pkey")),
        sa.UniqueConstraint("handle", name=op.f("agents_handle_key")),
    )
    op.create_index(op.f("agents_is_template_idx"), "agents", ["is_template"], unique=False)
    op.create_table(
        "app_users",
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("username", sa.Text(), nullable=False),
        sa.Column("password_hash", sa.Text(), nullable=False),
        sa.Column("display_name", sa.Text(), nullable=False),
        sa.Column("role", sa.Text(), server_default="builder", nullable=False),
        sa.Column("is_active", sa.Boolean(), server_default="true", nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.CheckConstraint("role IN ('builder')", name=op.f("app_users_role_check")),
        sa.PrimaryKeyConstraint("id", name=op.f("app_users_pkey")),
        sa.UniqueConstraint("username", name=op.f("app_users_username_key")),
    )
    op.create_table(
        "firms",
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("name", sa.Text(), nullable=False),
        sa.Column("slug", sa.Text(), nullable=False),
        sa.Column("timezone", sa.Text(), nullable=False),
        sa.Column("status", sa.Text(), server_default="active", nullable=False),
        sa.Column("color", sa.Text(), nullable=False),
        sa.Column(
            "settings", postgresql.JSONB(astext_type=sa.Text()), server_default="{}", nullable=False
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.CheckConstraint("slug ~ '^[a-z0-9-]{2,40}$'", name=op.f("firms_slug_format_check")),
        sa.CheckConstraint("status IN ('active','inactive')", name=op.f("firms_status_check")),
        sa.PrimaryKeyConstraint("id", name=op.f("firms_pkey")),
        sa.UniqueConstraint("slug", name=op.f("firms_slug_key")),
    )
    op.create_table(
        "registry_entries",
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("kind", sa.Text(), nullable=False),
        sa.Column("name", sa.Text(), nullable=False),
        sa.Column("connector", sa.Text(), nullable=True),
        sa.Column("display_name", sa.Text(), nullable=False),
        sa.Column("description", sa.Text(), server_default="", nullable=False),
        sa.Column(
            "params_schema",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default="{}",
            nullable=False,
        ),
        sa.Column("risk_tier", sa.Text(), nullable=True),
        sa.Column("direction", sa.Text(), nullable=True),
        sa.Column("is_async", sa.Boolean(), server_default="false", nullable=False),
        sa.Column("available", sa.Boolean(), server_default="true", nullable=False),
        sa.Column("version", sa.Integer(), server_default="1", nullable=False),
        sa.Column("synced_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.CheckConstraint(
            "direction IS NULL OR direction IN ('inbound','outbound')",
            name=op.f("registry_entries_direction_check"),
        ),
        sa.CheckConstraint(
            "kind IN ('connector','tool','policy_rule','channel','evidence_kind')",
            name=op.f("registry_entries_kind_check"),
        ),
        sa.CheckConstraint(
            "risk_tier IS NULL OR risk_tier IN ('read','internal_write','external_comm')",
            name=op.f("registry_entries_risk_tier_check"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("registry_entries_pkey")),
        sa.UniqueConstraint("kind", "name", name=op.f("registry_entries_kind_name_key")),
    )
    op.create_index(
        op.f("registry_entries_connector_idx"), "registry_entries", ["connector"], unique=False
    )
    op.create_table(
        "agent_prompts",
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("agent_id", sa.UUID(), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("status", sa.Text(), server_default="active", nullable=False),
        sa.Column("config", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("config_hash", sa.Text(), nullable=False),
        sa.Column("parent_version_id", sa.UUID(), nullable=True),
        sa.Column("changelog", sa.Text(), server_default="", nullable=False),
        sa.Column("created_by", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.CheckConstraint(
            "status IN ('active','archived')", name=op.f("agent_prompts_status_check")
        ),
        sa.CheckConstraint("version >= 1", name=op.f("agent_prompts_version_positive_check")),
        sa.ForeignKeyConstraint(
            ["agent_id"], ["agents.id"], name=op.f("agent_prompts_agent_id_fkey")
        ),
        sa.ForeignKeyConstraint(
            ["created_by"], ["app_users.id"], name=op.f("agent_prompts_created_by_fkey")
        ),
        sa.ForeignKeyConstraint(
            ["parent_version_id"],
            ["agent_prompts.id"],
            name=op.f("agent_prompts_parent_version_id_fkey"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("agent_prompts_pkey")),
        sa.UniqueConstraint("agent_id", "version", name=op.f("agent_prompts_agent_id_version_key")),
    )
    op.create_table(
        "connector_connections",
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("firm_id", sa.UUID(), nullable=False),
        sa.Column("connector", sa.Text(), nullable=False),
        sa.Column("label", sa.Text(), nullable=False),
        sa.Column("status", sa.Text(), server_default="pending", nullable=False),
        sa.Column(
            "config", postgresql.JSONB(astext_type=sa.Text()), server_default="{}", nullable=False
        ),
        sa.Column("encrypted_secrets", sa.Text(), nullable=True),
        sa.Column(
            "secret_hints",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default="{}",
            nullable=False,
        ),
        sa.Column("consent_nonce", sa.Text(), nullable=True),
        sa.Column("connected_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("health", sa.Text(), server_default="unknown", nullable=False),
        sa.Column(
            "test_results",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default="{}",
            nullable=False,
        ),
        sa.Column("last_tested_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_inbound_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_inbound_type", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.CheckConstraint(
            "health IN ('unknown','ok','degraded','revoked')",
            name=op.f("connector_connections_health_check"),
        ),
        sa.CheckConstraint(
            "status IN ('pending','connected','error')",
            name=op.f("connector_connections_status_check"),
        ),
        sa.ForeignKeyConstraint(
            ["firm_id"], ["firms.id"], name=op.f("connector_connections_firm_id_fkey")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("connector_connections_pkey")),
    )
    op.create_index(
        "connector_connections_firm_id_connector_idx",
        "connector_connections",
        ["firm_id", "connector"],
        unique=False,
    )
    op.create_table(
        "compiled_agent_firm_mappings",
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("agent_prompt_id", sa.UUID(), nullable=False),
        sa.Column("agent_id", sa.UUID(), nullable=False),
        sa.Column("firm_id", sa.UUID(), nullable=False),
        sa.Column(
            "identities",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default="{}",
            nullable=False,
        ),
        sa.Column(
            "overrides",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default="{}",
            nullable=False,
        ),
        sa.Column("ab_weight", sa.Integer(), server_default="100", nullable=False),
        sa.Column("status", sa.Text(), server_default="inactive", nullable=False),
        sa.Column("kill_switch", sa.Boolean(), server_default="false", nullable=False),
        sa.Column("supersedes_mapping_id", sa.UUID(), nullable=True),
        sa.Column("mapped_by", sa.UUID(), nullable=False),
        sa.Column(
            "mapped_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.CheckConstraint(
            "status IN ('active','inactive')",
            name=op.f("compiled_agent_firm_mappings_status_check"),
        ),
        sa.CheckConstraint(
            "ab_weight BETWEEN 0 AND 100", name=op.f("compiled_agent_firm_mappings_ab_weight_check")
        ),
        sa.ForeignKeyConstraint(
            ["agent_id"], ["agents.id"], name=op.f("compiled_agent_firm_mappings_agent_id_fkey")
        ),
        sa.ForeignKeyConstraint(
            ["agent_prompt_id"],
            ["agent_prompts.id"],
            name=op.f("compiled_agent_firm_mappings_agent_prompt_id_fkey"),
        ),
        sa.ForeignKeyConstraint(
            ["firm_id"], ["firms.id"], name=op.f("compiled_agent_firm_mappings_firm_id_fkey")
        ),
        sa.ForeignKeyConstraint(
            ["mapped_by"],
            ["app_users.id"],
            name=op.f("compiled_agent_firm_mappings_mapped_by_fkey"),
        ),
        sa.ForeignKeyConstraint(
            ["supersedes_mapping_id"],
            ["compiled_agent_firm_mappings.id"],
            name=op.f("compiled_agent_firm_mappings_supersedes_mapping_id_fkey"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("compiled_agent_firm_mappings_pkey")),
    )
    op.create_index(
        "compiled_agent_firm_mappings_active_firm_id_agent_id_key",
        "compiled_agent_firm_mappings",
        ["firm_id", "agent_id"],
        unique=True,
        postgresql_where="status = 'active'",
    )
    op.create_index(
        op.f("compiled_agent_firm_mappings_firm_id_idx"),
        "compiled_agent_firm_mappings",
        ["firm_id"],
        unique=False,
    )
    # ### end Alembic commands ###
    op.execute(SEARCH_INDEX)
    for statement in TRIGGERS:
        op.execute(statement)


def downgrade() -> None:
    """Downgrade schema."""
    for statement in DROP_TRIGGERS:
        op.execute(statement)
    op.execute("DROP INDEX IF EXISTS agents_search_trgm_idx")
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("compiled_agent_firm_mappings_firm_id_idx"), table_name="compiled_agent_firm_mappings"
    )
    op.drop_index(
        "compiled_agent_firm_mappings_active_firm_id_agent_id_key",
        table_name="compiled_agent_firm_mappings",
        postgresql_where="status = 'active'",
    )
    op.drop_table("compiled_agent_firm_mappings")
    op.drop_index("connector_connections_firm_id_connector_idx", table_name="connector_connections")
    op.drop_table("connector_connections")
    op.drop_table("agent_prompts")
    op.drop_index(op.f("registry_entries_connector_idx"), table_name="registry_entries")
    op.drop_table("registry_entries")
    op.drop_table("firms")
    op.drop_table("app_users")
    op.drop_index(op.f("agents_is_template_idx"), table_name="agents")
    op.drop_table("agents")
    # ### end Alembic commands ###
