"""subjects contacts

Revision ID: 0002
Revises: 0001
Create Date: 2026-10-02 19:42:56.054816

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "0002"
down_revision: str | Sequence[str] | None = "0001"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


# Fuzzy subject shortlist (ORCHESTRATOR_SPEC §4.1); listed in db/manual.py.
TRGM_INDEXES = [
    "CREATE INDEX subjects_title_trgm_idx ON subjects USING gin (title gin_trgm_ops)",
    "CREATE INDEX subjects_external_ref_trgm_idx ON subjects USING gin (external_ref gin_trgm_ops)",
    "CREATE INDEX contact_points_name_trgm_idx ON contact_points USING gin (name gin_trgm_ops)",
]


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "contact_points",
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("firm_id", sa.UUID(), nullable=False),
        sa.Column("name", sa.Text(), nullable=False),
        sa.Column("org_name", sa.Text(), nullable=True),
        sa.Column("emails", postgresql.ARRAY(sa.Text()), server_default="{}", nullable=False),
        sa.Column(
            "phones", postgresql.JSONB(astext_type=sa.Text()), server_default="[]", nullable=False
        ),
        sa.Column("tz", sa.Text(), nullable=True),
        sa.Column(
            "opt_out", postgresql.JSONB(astext_type=sa.Text()), server_default="{}", nullable=False
        ),
        sa.Column("org_daily_cap", sa.Integer(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["firm_id"], ["firms.id"], name=op.f("contact_points_firm_id_fkey")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("contact_points_pkey")),
        sa.UniqueConstraint("id", "firm_id", name=op.f("contact_points_id_firm_id_key")),
    )
    op.create_table(
        "subjects",
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("firm_id", sa.UUID(), nullable=False),
        sa.Column("kind", sa.Text(), nullable=False),
        sa.Column("title", sa.Text(), nullable=False),
        sa.Column("external_ref", sa.Text(), nullable=True),
        sa.Column("status", sa.Text(), server_default="open", nullable=False),
        sa.Column("description", sa.Text(), server_default="", nullable=False),
        sa.Column(
            "data", postgresql.JSONB(astext_type=sa.Text()), server_default="{}", nullable=False
        ),
        sa.Column("revision", sa.Integer(), server_default="1", nullable=False),
        sa.Column("created_by", sa.UUID(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.CheckConstraint("kind ~ '^[a-z0-9 _-]{1,40}$'", name=op.f("subjects_kind_format_check")),
        sa.CheckConstraint("status IN ('open','closed')", name=op.f("subjects_status_check")),
        sa.ForeignKeyConstraint(
            ["created_by"], ["app_users.id"], name=op.f("subjects_created_by_fkey")
        ),
        sa.ForeignKeyConstraint(["firm_id"], ["firms.id"], name=op.f("subjects_firm_id_fkey")),
        sa.PrimaryKeyConstraint("id", name=op.f("subjects_pkey")),
        sa.UniqueConstraint("id", "firm_id", name=op.f("subjects_id_firm_id_key")),
    )
    op.create_index(
        "subjects_firm_id_external_ref_key",
        "subjects",
        ["firm_id", "external_ref"],
        unique=True,
        postgresql_where="external_ref IS NOT NULL",
    )
    op.create_index("subjects_firm_id_status_idx", "subjects", ["firm_id", "status"], unique=False)
    op.create_table(
        "subject_contacts",
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("firm_id", sa.UUID(), nullable=False),
        sa.Column("subject_id", sa.UUID(), nullable=False),
        sa.Column("contact_point_id", sa.UUID(), nullable=False),
        sa.Column("role", sa.Text(), nullable=False),
        sa.Column(
            "consent", postgresql.JSONB(astext_type=sa.Text()), server_default="{}", nullable=False
        ),
        sa.Column("alias_ordinal", sa.Integer(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.CheckConstraint(
            "role IN ('client','provider','insurer','prospect','other')",
            name=op.f("subject_contacts_role_check"),
        ),
        sa.ForeignKeyConstraint(
            ["contact_point_id", "firm_id"],
            ["contact_points.id", "contact_points.firm_id"],
            name=op.f("subject_contacts_contact_point_id_fkey"),
        ),
        sa.ForeignKeyConstraint(
            ["firm_id"], ["firms.id"], name=op.f("subject_contacts_firm_id_fkey")
        ),
        sa.ForeignKeyConstraint(
            ["subject_id", "firm_id"],
            ["subjects.id", "subjects.firm_id"],
            name=op.f("subject_contacts_subject_id_fkey"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("subject_contacts_pkey")),
        sa.UniqueConstraint(
            "subject_id",
            "contact_point_id",
            "role",
            name=op.f("subject_contacts_subject_id_contact_point_id_role_key"),
        ),
    )
    # ### end Alembic commands ###
    for sql in TRGM_INDEXES:
        op.execute(sql)


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("subject_contacts")
    op.drop_index("subjects_firm_id_status_idx", table_name="subjects")
    op.drop_index(
        "subjects_firm_id_external_ref_key",
        table_name="subjects",
        postgresql_where="external_ref IS NOT NULL",
    )
    op.drop_table("subjects")
    op.drop_table("contact_points")
    # ### end Alembic commands ###
