"""conversations messages

Revision ID: 0003
Revises: 0002
Create Date: 2026-10-02 19:43:49.462881

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "0003"
down_revision: str | Sequence[str] | None = "0002"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


# A conversation's subject is set once, then locked (D4). One statement per entry (asyncpg).
MANUAL = [
    """
    CREATE FUNCTION conversations_subject_locked() RETURNS trigger AS $$
    BEGIN
      IF OLD.subject_id IS NOT NULL AND NEW.subject_id IS DISTINCT FROM OLD.subject_id THEN
        RAISE EXCEPTION 'conversation subject is locked' USING ERRCODE = 'check_violation';
      END IF;
      RETURN NEW;
    END $$ LANGUAGE plpgsql
    """,
    """
    CREATE TRIGGER conversations_subject_locked BEFORE UPDATE ON conversations
      FOR EACH ROW EXECUTE FUNCTION conversations_subject_locked()
    """,
    "CREATE INDEX conversations_title_trgm_idx ON conversations USING gin (title gin_trgm_ops)",
]


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "conversations",
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("firm_id", sa.UUID(), nullable=False),
        sa.Column("channel", sa.Text(), nullable=False),
        sa.Column("subject_id", sa.UUID(), nullable=True),
        sa.Column("title", sa.Text(), nullable=True),
        sa.Column("external_thread_ref", sa.Text(), nullable=True),
        sa.Column(
            "state", postgresql.JSONB(astext_type=sa.Text()), server_default="{}", nullable=False
        ),
        sa.Column("created_by", sa.UUID(), nullable=True),
        sa.Column(
            "last_message_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.CheckConstraint(
            "channel IN ('playground','slack','voice','email','api')",
            name=op.f("conversations_channel_check"),
        ),
        sa.ForeignKeyConstraint(
            ["created_by"], ["app_users.id"], name=op.f("conversations_created_by_fkey")
        ),
        sa.ForeignKeyConstraint(["firm_id"], ["firms.id"], name=op.f("conversations_firm_id_fkey")),
        sa.ForeignKeyConstraint(
            ["subject_id", "firm_id"],
            ["subjects.id", "subjects.firm_id"],
            name=op.f("conversations_subject_id_fkey"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("conversations_pkey")),
        sa.UniqueConstraint(
            "firm_id",
            "channel",
            "external_thread_ref",
            name=op.f("conversations_firm_id_channel_external_thread_ref_key"),
        ),
        sa.UniqueConstraint("id", "firm_id", name=op.f("conversations_id_firm_id_key")),
    )
    op.create_index(
        "conversations_firm_id_last_message_at_idx",
        "conversations",
        ["firm_id", "last_message_at"],
        unique=False,
    )
    op.create_table(
        "messages",
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("firm_id", sa.UUID(), nullable=False),
        sa.Column("conversation_id", sa.UUID(), nullable=False),
        sa.Column("seq", sa.BigInteger(), sa.Identity(always=False), nullable=False),
        sa.Column("direction", sa.Text(), nullable=False),
        sa.Column("actor", sa.Text(), nullable=False),
        sa.Column("author_user_id", sa.UUID(), nullable=True),
        sa.Column("external_author", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("agent_id", sa.UUID(), nullable=True),
        sa.Column("run_id", sa.UUID(), nullable=True),
        sa.Column("body", sa.Text(), nullable=False),
        sa.Column("mentions", postgresql.ARRAY(sa.Text()), server_default="{}", nullable=False),
        sa.Column(
            "blocks", postgresql.JSONB(astext_type=sa.Text()), server_default="[]", nullable=False
        ),
        sa.Column("status", sa.Text(), nullable=False),
        sa.Column("external_ref", sa.Text(), nullable=True),
        sa.Column("dedup_key", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.CheckConstraint(
            "actor IN ('human','agent','system','contact')", name=op.f("messages_actor_check")
        ),
        sa.CheckConstraint(
            "direction IN ('inbound','outbound','internal')", name=op.f("messages_direction_check")
        ),
        sa.CheckConstraint(
            "status IN ('received','queued','sent','failed')", name=op.f("messages_status_check")
        ),
        sa.ForeignKeyConstraint(["agent_id"], ["agents.id"], name=op.f("messages_agent_id_fkey")),
        sa.ForeignKeyConstraint(
            ["author_user_id"], ["app_users.id"], name=op.f("messages_author_user_id_fkey")
        ),
        sa.ForeignKeyConstraint(
            ["conversation_id", "firm_id"],
            ["conversations.id", "conversations.firm_id"],
            name=op.f("messages_conversation_id_fkey"),
        ),
        sa.ForeignKeyConstraint(["firm_id"], ["firms.id"], name=op.f("messages_firm_id_fkey")),
        sa.PrimaryKeyConstraint("id", name=op.f("messages_pkey")),
        sa.UniqueConstraint("seq", name=op.f("messages_seq_key")),
        sa.UniqueConstraint("dedup_key", name=op.f("messages_dedup_key_key")),
    )
    op.create_index(
        "messages_conversation_id_seq_idx",
        "messages",
        ["conversation_id", "seq"],
        unique=False,
    )
    # ### end Alembic commands ###
    for sql in MANUAL:
        op.execute(sql)


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("messages_conversation_id_seq_idx", table_name="messages")
    op.drop_table("messages")
    op.drop_index("conversations_firm_id_last_message_at_idx", table_name="conversations")
    op.drop_table("conversations")
    # ### end Alembic commands ###
    op.execute("DROP FUNCTION conversations_subject_locked")
