"""runs tasks episodes

Revision ID: 0004
Revises: 0003
Create Date: 2026-10-02 19:45:20.152054

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "0004"
down_revision: str | Sequence[str] | None = "0003"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(
        op.f("compiled_agent_firm_mappings_id_firm_id_key"),
        "compiled_agent_firm_mappings",
        ["id", "firm_id"],
    )
    op.create_table(
        "agent_runs",
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("firm_id", sa.UUID(), nullable=False),
        sa.Column("mapping_id", sa.UUID(), nullable=False),
        sa.Column("agent_id", sa.UUID(), nullable=False),
        sa.Column("agent_prompt_id", sa.UUID(), nullable=False),
        sa.Column("subject_id", sa.UUID(), nullable=False),
        sa.Column("status", sa.Text(), server_default="CREATED", nullable=False),
        sa.Column("substatus", sa.Text(), nullable=True),
        sa.Column("origin", sa.Text(), nullable=False),
        sa.Column("goal", sa.Text(), server_default="", nullable=False),
        sa.Column("completion_criteria", sa.Text(), server_default="", nullable=False),
        sa.Column(
            "state", postgresql.JSONB(astext_type=sa.Text()), server_default="{}", nullable=False
        ),
        sa.Column("takeover", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("cycle", sa.Integer(), server_default="0", nullable=False),
        sa.Column("step_count", sa.Integer(), server_default="0", nullable=False),
        sa.Column("next_wake_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("lease_owner", sa.Text(), nullable=True),
        sa.Column("lease_epoch", sa.BigInteger(), server_default="0", nullable=False),
        sa.Column("lease_expires_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("ended_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("ended_reason", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.CheckConstraint(
            "(status = 'ACTIVE' AND coalesce(substatus IN ('RUNNING','WAITING','ATTENTION'), true)) OR (status = 'PAUSED' AND substatus IN ('kill_switch','repeated_failure','subject_closed')) OR (status NOT IN ('ACTIVE','PAUSED') AND substatus IS NULL)",
            name=op.f("agent_runs_substatus_check"),
        ),
        sa.CheckConstraint(
            "origin IN ('playground','slack','api','schedule')",
            name=op.f("agent_runs_origin_check"),
        ),
        sa.CheckConstraint(
            "status IN ('CREATED','ACTIVE','TAKEN_OVER','PAUSED','AWAITING_CONFIRMATION','COMPLETED','ENDED','FAILED')",
            name=op.f("agent_runs_status_check"),
        ),
        sa.ForeignKeyConstraint(["agent_id"], ["agents.id"], name=op.f("agent_runs_agent_id_fkey")),
        sa.ForeignKeyConstraint(
            ["agent_prompt_id"], ["agent_prompts.id"], name=op.f("agent_runs_agent_prompt_id_fkey")
        ),
        sa.ForeignKeyConstraint(["firm_id"], ["firms.id"], name=op.f("agent_runs_firm_id_fkey")),
        sa.ForeignKeyConstraint(
            ["mapping_id", "firm_id"],
            ["compiled_agent_firm_mappings.id", "compiled_agent_firm_mappings.firm_id"],
            name=op.f("agent_runs_mapping_id_fkey"),
        ),
        sa.ForeignKeyConstraint(
            ["subject_id", "firm_id"],
            ["subjects.id", "subjects.firm_id"],
            name=op.f("agent_runs_subject_id_fkey"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("agent_runs_pkey")),
        sa.UniqueConstraint("id", "firm_id", name=op.f("agent_runs_id_firm_id_key")),
    )
    op.create_index(
        "agent_runs_firm_id_status_idx", "agent_runs", ["firm_id", "status"], unique=False
    )
    op.create_index(
        "agent_runs_one_active",
        "agent_runs",
        ["agent_id", "subject_id"],
        unique=True,
        postgresql_where="status IN ('CREATED','ACTIVE','TAKEN_OVER','PAUSED','AWAITING_CONFIRMATION')",
    )
    op.create_index("agent_runs_subject_id_idx", "agent_runs", ["subject_id"], unique=False)
    op.create_table(
        "run_tasks",
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("firm_id", sa.UUID(), nullable=False),
        sa.Column("run_id", sa.UUID(), nullable=False),
        sa.Column("key", sa.Text(), nullable=False),
        sa.Column("kind", sa.Text(), nullable=False),
        sa.Column("target", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("title", sa.Text(), nullable=False),
        sa.Column("goal", sa.Text(), nullable=False),
        sa.Column(
            "input", postgresql.JSONB(astext_type=sa.Text()), server_default="{}", nullable=False
        ),
        sa.Column("status", sa.Text(), server_default="TODO", nullable=False),
        sa.Column("created_by", sa.Text(), nullable=False),
        sa.Column("origin_episode_id", sa.UUID(), nullable=True),
        sa.Column("depends_on", postgresql.ARRAY(sa.Text()), server_default="{}", nullable=False),
        sa.Column(
            "plan", postgresql.JSONB(astext_type=sa.Text()), server_default="[]", nullable=False
        ),
        sa.Column("plan_appends", sa.Integer(), server_default="0", nullable=False),
        sa.Column("output", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column(
            "follow_up",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default="{}",
            nullable=False,
        ),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("ended_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.CheckConstraint(
            "created_by IN ('triage','recurrence','human')", name=op.f("run_tasks_created_by_check")
        ),
        sa.CheckConstraint(
            "status IN ('TODO','IN_PROGRESS','WAITING','BLOCKED','DONE','SKIPPED','FAILED')",
            name=op.f("run_tasks_status_check"),
        ),
        sa.ForeignKeyConstraint(["firm_id"], ["firms.id"], name=op.f("run_tasks_firm_id_fkey")),
        sa.ForeignKeyConstraint(
            ["run_id", "firm_id"],
            ["agent_runs.id", "agent_runs.firm_id"],
            name=op.f("run_tasks_run_id_fkey"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("run_tasks_pkey")),
        sa.UniqueConstraint("id", "firm_id", name=op.f("run_tasks_id_firm_id_key")),
        sa.UniqueConstraint("run_id", "key", name=op.f("run_tasks_run_id_key_key")),
    )
    op.create_index("run_tasks_run_id_status_idx", "run_tasks", ["run_id", "status"], unique=False)
    op.create_table(
        "episodes",
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("firm_id", sa.UUID(), nullable=False),
        sa.Column("run_id", sa.UUID(), nullable=False),
        sa.Column("task_id", sa.UUID(), nullable=True),
        sa.Column("trigger_type", sa.Text(), nullable=False),
        sa.Column("status", sa.Text(), nullable=False),
        sa.Column("source", sa.Text(), nullable=True),
        sa.Column(
            "metadata", postgresql.JSONB(astext_type=sa.Text()), server_default="{}", nullable=False
        ),
        sa.Column("dedup_key", sa.Text(), nullable=False),
        sa.Column("due_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("reason", sa.Text(), nullable=True),
        sa.Column("rung", sa.Integer(), nullable=True),
        sa.Column("attempt", sa.Integer(), nullable=True),
        sa.Column("guard_version", sa.Integer(), server_default="0", nullable=False),
        sa.Column("celery_task_id", sa.Text(), nullable=True),
        sa.Column("lease_epoch", sa.BigInteger(), nullable=True),
        sa.Column("queued_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("ended_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("outcome", sa.Text(), nullable=True),
        sa.Column("tokens", sa.Integer(), server_default="0", nullable=False),
        sa.Column("cost", sa.Numeric(precision=12, scale=6), server_default="0", nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.CheckConstraint(
            "(trigger_type = 'scheduled') = (source IS NOT NULL)",
            name=op.f("episodes_source_iff_check"),
        ),
        sa.CheckConstraint("dedup_key ~ '^[a-z_]+:'", name=op.f("episodes_dedup_key_format_check")),
        sa.CheckConstraint(
            "source IS NULL OR source IN ('ladder','dynamic','recurrence','deferral','retry','plan_wait','reconcile')",
            name=op.f("episodes_source_check"),
        ),
        sa.CheckConstraint(
            "status IN ('scheduled','armed','pending','deferred','running','completed','failed','superseded')",
            name=op.f("episodes_status_check"),
        ),
        sa.CheckConstraint(
            "trigger_type IN ('scheduled','user_input','user_response','external_response','handback','retry','delegation')",
            name=op.f("episodes_trigger_type_check"),
        ),
        sa.ForeignKeyConstraint(["firm_id"], ["firms.id"], name=op.f("episodes_firm_id_fkey")),
        sa.ForeignKeyConstraint(
            ["run_id", "firm_id"],
            ["agent_runs.id", "agent_runs.firm_id"],
            name=op.f("episodes_run_id_fkey"),
        ),
        sa.ForeignKeyConstraint(["task_id"], ["run_tasks.id"], name=op.f("episodes_task_id_fkey")),
        sa.PrimaryKeyConstraint("id", name=op.f("episodes_pkey")),
        sa.UniqueConstraint("dedup_key", name=op.f("episodes_dedup_key_key")),
    )
    op.create_index(
        "episodes_arm_idx",
        "episodes",
        ["due_at"],
        unique=False,
        postgresql_where="status = 'scheduled'",
    )
    op.create_index(
        "episodes_live_followup_key",
        "episodes",
        ["task_id"],
        unique=True,
        postgresql_where="status IN ('scheduled','armed') AND source IN ('ladder','dynamic')",
    )
    op.create_index(
        "episodes_one_running_key",
        "episodes",
        ["run_id"],
        unique=True,
        postgresql_where="status = 'running'",
    )
    op.create_index(
        "episodes_pending_idx",
        "episodes",
        ["run_id", "queued_at"],
        unique=False,
        postgresql_where="status = 'pending'",
    )
    op.create_index(
        "episodes_refire_idx",
        "episodes",
        ["due_at"],
        unique=False,
        postgresql_where="status = 'armed'",
    )
    # ### end Alembic commands ###
    # Linked conversations (CHANNELS_SPEC §3.3); listed in db/manual.py.
    op.execute(
        "CREATE INDEX episodes_conversation_idx ON episodes ((metadata->>'conversation_id'))"
        " WHERE metadata ? 'conversation_id'"
    )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("episodes_refire_idx", table_name="episodes", postgresql_where="status = 'armed'")
    op.drop_index(
        "episodes_pending_idx", table_name="episodes", postgresql_where="status = 'pending'"
    )
    op.drop_index(
        "episodes_one_running_key", table_name="episodes", postgresql_where="status = 'running'"
    )
    op.drop_index(
        "episodes_live_followup_key",
        table_name="episodes",
        postgresql_where="status IN ('scheduled','armed') AND source IN ('ladder','dynamic')",
    )
    op.drop_index(
        "episodes_arm_idx", table_name="episodes", postgresql_where="status = 'scheduled'"
    )
    op.drop_table("episodes")
    op.drop_index("run_tasks_run_id_status_idx", table_name="run_tasks")
    op.drop_table("run_tasks")
    op.drop_index("agent_runs_subject_id_idx", table_name="agent_runs")
    op.drop_index(
        "agent_runs_one_active",
        table_name="agent_runs",
        postgresql_where="status IN ('CREATED','ACTIVE','TAKEN_OVER','PAUSED','AWAITING_CONFIRMATION')",
    )
    op.drop_index("agent_runs_firm_id_status_idx", table_name="agent_runs")
    op.drop_table("agent_runs")
    op.drop_constraint(
        op.f("compiled_agent_firm_mappings_id_firm_id_key"),
        "compiled_agent_firm_mappings",
        type_="unique",
    )
    # ### end Alembic commands ###
